### ISSUE TITLE
[BUG] 获取应用列表时panic

### ISSUE THREAD

**Issue by ChnMig** [TongchengOpenSource/AppScan#48]
## Appscan 版本
> 请填写目前使用的AppScan的精确版本号

2.1.2

## 系统版本

电脑版本:
> 例如 win10

11
手机型号:
> 例如 红米K40

红米k40
安卓版本:
> 例如 安卓11

12

## Bug 描述
> 请充分描述Bug的现象和复现步骤

初始化时卡在 获取软件列表 步骤
日志显示报错

Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 78, in __call__
  File "fastapi\applications.py", line 270, in __call__
  File "starlette\applications.py", line 124, in __call__
  File "starlette\middleware\errors.py", line 184, in __call__
  File "starlette\middleware\errors.py", line 162, in __call__
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\middleware\exceptions.py", line 75, in __call__
  File "starlette\middleware\exceptions.py", line 64, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 21, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 18, in __call__
  File "starlette\routing.py", line 680, in __call__
  File "starlette\routing.py", line 275, in handle
  File "starlette\routing.py", line 65, in app
  File "fastapi\routing.py", line 235, in app
  File "fastapi\routing.py", line 161, in run_endpoint_function
  File "routers\frida\app.py", line 51, in getApps
KeyError: 'version'

**Comment by ChnMig** [comment]
2.1.2发布
