### ISSUE TITLE
helper问题

### ISSUE THREAD

**Issue by feichuanshuo** [TongchengOpenSource/AppScan#63]
当我尝试使用http://www.websocket-test.com/测试websocket时，helper提示如下错误
INFO:     Started server process [12440]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8848 (Press CTRL+C to quit)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 230, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\starlette\middleware\cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 51, in __call__
    await self.app(scope, receive, send)
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\starlette\routing.py", line 427, in handle
    await self.app(scope, receive, send)
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\engineio\async_drivers\asgi.py", line 69, in __call__
    await self.not_found(receive, send)
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\engineio\async_drivers\asgi.py", line 117, in not_found
    await send({'type': 'http.response.start',
  File "E:\Project\AppScan\helper\venv\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 293, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Expected ASGI message 'websocket.accept' or 'websocket.close', but got 'http.response.start'.
直接请求ws://0.0.0.0:8848便发生了上述情况，小白求大佬解读！！！

**Comment by ChnMig** [comment]
链接 ws://127.0.0.1:8848/api/v1/frida/hook/ws 呢?

**Comment by feichuanshuo** [comment]
提示同样的错误

**Comment by ChnMig** [comment]
> RuntimeError: Expected ASGI message 'websocket.accept' or 'websocket.close', but got 'http.response.start'.

感觉像是客户端和服务端的协议对接出错, 你要不试试用postman这种其他的支持ws的客户端试试, 如果一样请检查一下heleper是不是正确启动了

**Comment by ChnMig** [comment]
长时间未收到回复, 此issue暂时关闭
