### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hectongh** [TongchengOpenSource/AppScan#71]
## Appscan 版本
2.1.5

## 系统版本

电脑版本:
Win10

手机型号:
Huawei P9

安卓版本:
安卓7

## Bug 描述
授权后点击开始检测无法拉起对应app，日志见下方

**helper.log**
`[2024-07-22T17:43:23.568] [INFO] default - INFO:     Started server process [30108]
INFO:     Waiting for application startup.

[2024-07-22T17:43:23.569] [INFO] default - INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:50000 (Press CTRL+C to quit)

[2024-07-22T17:43:26.793] [INFO] default - * daemon not running; starting now at tcp:5037

[2024-07-22T17:43:29.811] [INFO] default - * daemon started successfully

[2024-07-22T17:43:34.958] [INFO] default - setprop: name 'persist.device_config.runtime_native.usap_pool_enabled' too long; try 'persist.device_config.runtime_n'

[2024-07-22T17:43:35.007] [INFO] default - usage: pkill [-l SIGNAL] [PATTERN]

-l	SIGNAL to send
-V	verbose

pkill: Unknown option 9

[2024-07-22T17:43:46.541] [INFO] default - unable to stat file for the executable "/memfd:frida-helper-32 (deleted)": No such file or directory

[2024-07-22T17:44:10.428] [INFO] default - INFO:     ('127.0.0.1', 2972) - "WebSocket /socket.io/?EIO=4&transport=websocket" [accepted]

[2024-07-22T17:44:10.428] [INFO] default - INFO:     connection open

[2024-07-22T17:44:20.831] [INFO] default - ERROR:root:Traceback (most recent call last):
  File "internal\hook\hook.py", line 62, in _hook
  File "frida\core.py", line 86, in wrapper
  File "frida\core.py", line 968, in spawn
frida.TimedOutError: unexpectedly timed out while spawning helper process

ERROR:root:{'type': 'helper_error', 'data': 'Traceback (most recent call last):\n  File "internal\\hook\\hook.py", line 62, in _hook\n  File "frida\\core.py", line 86, in wrapper\n  File "frida\\core.py", line 968, in spawn\nfrida.TimedOutError: unexpectedly timed out while spawning helper process\n'}

`

**frida.log**
`format = '2024-07-22 17:44:20,830 - root - ERROR - Traceback (most recent call last):
  File "internal\hook\hook.py", line 62, in _hook
  File "frida\core.py", line 86, in wrapper
  File "frida\core.py", line 968, in spawn
frida.TimedOutError: unexpectedly timed out while spawning helper process
-_hook',
format = '2024-07-22 17:44:20,831 - root - ERROR - {'type': 'helper_error', 'data': 'Traceback (most recent call last):\n  File "internal\\hook\\hook.py", line 62, in _hook\n  File "frida\\core.py", line 86, in wrapper\n  File "frida\\core.py", line 968, in spawn\nfrida.TimedOutError: unexpectedly timed out while spawning helper process\n'}-send_data',
`

**Comment by ChnMig** [comment]
通过日志看是有些初始化命令没有执行成功, 有其他手机设备可以测试吗

**Comment by hectongh** [comment]
已经找到问题了，系统版本是7.0的，升级到8.0就可以了，但是新问题出现了，

Appscan提示：未找到设备：unable to perform ptrace pokedata:I/O error

**Comment by ChnMig** [comment]
> 已经找到问题了，系统版本是7.0的，升级到8.0就可以了，但是新问题出现了，
> 
> Appscan提示：未找到设备：unable to perform ptrace pokedata:I/O error

感谢回复, 请问日志文件中还有错误的上下文吗?

**Comment by hectongh** [comment]
日志中无其他错误，只有Appscan在连接设备的时候报了这个错误
